### ISSUE TITLE
Timestamp?

### ISSUE THREAD

**Issue by jeokeefe** [adamczykpiotr/php-canbus#2]
the candump utility provide a timestamp with the NMEa message.  Any way to get this timestamp?

**Comment by adamczykpiotr** [comment]
This library doesn't provide any timestamp information for a frame. Usually there is little to no delay between receiving frame by a machine so you could use `time()` or `new DateTime()`. If your protocol is layer above CAN, you could always manually parse CAN frame yourself to obtain transmitted timestamp.
